name: Auto update

on:
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt-get install openssh-client python3-setuptools

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          repository: jackjyq/genpac
          path: genpac

      - uses: actions/checkout@v3
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      - uses: petronny/git-config-user@master
        with:
          path: .

      - run: |
          cd genpac
          sudo python3 setup.py install

      - name: Update
        run: |
          set -x

          genpac --pac-proxy "SOCKS5 127.0.0.1:1081; SOCKS 127.0.0.1:1081; DIRECT;" --gfwlist-url - --gfwlist-local gfwlist/gfwlist.txt -o gfwlist.js

          git add gfwlist.js
          git commit -m "[$(LANG=C date)] auto update" || exit 0

          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
