name: Update gfwlist.js

on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - uses: actions/checkout@v3
        with:
          repository: jackjyq/genpac
          path: genpac

      - uses: actions/checkout@v3
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      - uses: petronny/git-config-user@master
        with:
          path: .

      - run: |
          cd genpac
          sudo python3 setup.py install

      - name: Update
        run: |
          set -x

          genpac --pac-proxy "SOCKS5 127.0.0.1:1081; SOCKS 127.0.0.1:1081; DIRECT;" --gfwlist-url - --gfwlist-local gfwlist/gfwlist.txt -o gfwlist.js

          head -n 4 gfwlist.js | tail -n 2 > header && tail -n +3 README.md > body && cat header body > README.md
          git add gfwlist.js
          git commit -m "[$(LANG=C date)] auto update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
